version: '3'

services:

  db:
    build: 
      context: .
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: ["mysqld", 
    #   "--default-authentication-plugin=mysql_native_password",
    #   "--require_secure_transport=ON",
    #   "--bind-address=0.0.0.0",
    #   "--ssl-ca=/etc/certs/rootCA.pem",
    #   "--ssl-cert=/etc/certs/server.crt",
    #   "--ssl-key=/etc/certs/server.pkcs1.key",
    # ]
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      # - ./certs/:/etc/mysql/certs/
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080