SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS sampledb;

USE sampledb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- CREATE USER 'user1'@'%' IDENTIFIED BY 'Tibco@123';

-- GRANT ALL PRIVILEGES ON *.* TO 'user1'@'%' WITH GRANT OPTION;


CREATE USER 'onewayssl'@'%' IDENTIFIED by 'Tibco@123' REQUIRE SSL;
GRANT ALL PRIVILEGES on *.* TO 'onewayssl'@'%';


CREATE USER 'twowayssl'@'%' IDENTIFIED BY 'Tibco@123' REQUIRE X509;
GRANT ALL PRIVILEGES on *.* TO 'twowayssl'@'%';